### ISSUE TITLE
In Widget & Field Configuration add Widget selection drop down list

### ISSUE THREAD

**Issue by danutc** [clearbridgesoft/form-builder#9]
For example for string type field we can have many Widgets available to use. Example TextBox, TextArea, TextEditor etc.

Please add selection drop down list on Widget & Field Configuration pane. This allows to apply an widget to the field.

The drop down list shows all available widgets for the field type.

**Comment by bubuzzz** [comment]
Fixed in https://github.com/clearbridgesoft/form-builder/commit/1e2cb2ec7b6e58c39433f5ef713a9568f40313dd

**Comment by bubuzzz** [comment]
The editor is restructured a bit inside https://github.com/clearbridgesoft/form-builder/blob/develop/imports/form_builder/editor.jsx @knilink . At this moment, the json scheme editor only reflect the `configs` node of the `active` node, thus the name is not change yet. I think it is ok to pass the name inside the `configs` node and in the callback of the index.js, we gonna purify the `configs` again. What do you think ?

**Comment by bubuzzz** [comment]
`ui:widget` is set inside `uiEditPropertiesSchema`, so we will extend that strut once there is new component

**Comment by knilink** [comment]
@bubuzzz just add an another form for editing properties names so it should be ok. 
I still don't recommand to put name into 'configs'. If the form engine add some new feature in the future make the schema likes 
`
foo: {
  type: 'string',
  name: 'bar'
}
`
'foo',and 'bar' will conflict with each other in confis.

**Comment by hnandarusdy** [comment]
Please add the ui-widget for each schema type:
- String:  
   - <Rename> "default" to "Text Box"
   -  "Drop Down"
   - "Radio Button"
   - "WYSIWYG"

- Number / Integer. (Not sure why we have these two, probably we could eliminate one of them)
  - "Text box"
  - "Drop Down"

- Boolean
  - "Checkbox"

Add these components also: 
- Date 
- Date Time 
- Label

**Comment by hnandarusdy** [comment]
Still Missing: 
- String:
   - Drop down
   - Radio button
   - Checkbox 
   - WYSIWYG (only problem with style)

- Label

**BUG:** 
Boolean:
   - Checkbox 
      Errors: `Uncaught TypeError: formData.forEach is not a function`
   - Radio Button

Also, ui-widget should be displayed as a drop down list.
![image](https://cloud.githubusercontent.com/assets/14065403/17991994/da407e1e-6b86-11e6-9580-fd83a8dfd591.png)
